-- Create production API key for defarm-core
-- This key will have read permissions and higher rate limit

-- Generate a unique API key (in production, replace with actual bcrypt hash)
-- Key format: ck_[64 hex chars]
-- Example raw key: ck_prod_defarmcore_2026_a1b2c3d4e5f6...
-- This is a placeholder - actual key will be generated programmatically

-- For now, documenting the required structure:
INSERT INTO api_keys (
    name,
    key_prefix,
    key_hash,
    is_active,
    rate_limit,
    permissions,
    created_by,
    expires_at
) VALUES (
    'DeFarm Core - Production',
    'ck_prod_defa',  -- First 12 chars of the key
    -- key_hash should be bcrypt hash of the full key
    -- Example: $2b$10$... (will be generated by script)
    '$2b$10$PLACEHOLDER_HASH_TO_BE_REPLACED',
    true,
    10000,  -- 10,000 requests per minute (high limit for production)
    '["read", "write"]',  -- Full permissions
    'admin',
    NULL  -- No expiration
);

-- Note: This is a template. Use the Node.js script to generate the actual key with proper bcrypt hash.
